### ISSUE TITLE
Enter a GitHub username and view choices

### ISSUE THREAD

**Issue by surajverma2587** [surajverma2587/github-cli-app#1]
### User Story 

```
AS a user
WHEN I start the CLI application
THEN I am presented with a question to "Enter a GitHub username:"
AND WHEN I enter a valid GitHub Username
THEN I am presented with the choices shown below
```

#### Choices

```javascript
[
  {
    name: "Display information about <username>",
    value: "getUserInfo",
    short: "get user info",
  },
  {
    name: "List all repositories for <username>",
    value: "getAllRepos",
    short: "get repos",
  },
  {
    name: "List 10 recently created repositories for <username>",
    value: "getRecentlyCreatedRepos",
    short: "recently created repos",
  },
  {
    name: "List 10 recently updated repositories for <username>",
    value: "getRecentlyUpdatedRepos",
    short: "recently updated repos",
  },
  {
    name: "List all followers of <username>",
    value: "getFollowers",
    short: "get followers",
  },
  {
    name: "Find a repository by name",
    value: "getRepoByName",
    short: "find repo",
  },
  {
    name: "Enter a different username",
    value: "differentUsername",
    short: "different repo",
  },
  {
    name: "Exit",
    value: "exit",
    short: "exit",
  },
]
```

### Tasks

- [x] Setup node project (package.json, etc)
- [x] Install inquirer
- [x] prompt the user with the question
- [x] dynamically generate the choices for the given username
- [x] create a separate function for choice generation
- [x] add tests and jest framework
