### ISSUE TITLE
Should display information about a user

### ISSUE THREAD

**Issue by surajverma2587** [surajverma2587/github-cli-app#2]
### User Story

```
AS a user
WHEN I select the option of "Display information about <user_name>"
THEN I am presented with the information for the user as shown below
```

#### Expected Data

```json
{
  "type": "User",
  "name": "some name",
  "bio": "some bio",
  "company": "some company",
  "location": "some location",
  "username": "<user_name>",
  "profileUrl": "some_url",
  "public_repos": 10,
  "followers": 20,
  "following": 30,
  "created": "Mar 1st, 2017",
  "updated": "Jun 25th, 2020"
}
```

### GitHub API Link
https://api.github.com/users/YOUR_USERNAME

### Tasks

- [x] get username
- [ ] call function with username to fetch data from API
- [ ] data transformation of response to expected object
- [ ] console log the result
- [ ] add tests for the data transformation function
